import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-contact', standalone: true, imports: [FormsModule],
  template: `
    <section class="bg-primary-50 dark:bg-gray-800 border-b border-primary-100 dark:border-gray-700"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-20 text-center"><p class="text-primary-600 dark:text-primary-400 font-semibold text-sm tracking-widest uppercase">Contact</p><h1 class="mt-3 text-4xl sm:text-5xl font-display font-bold text-gray-900 dark:text-white">We are here to help.</h1><p class="mt-5 text-lg text-gray-600 dark:text-gray-300">Send us a message and our team will get back to you as soon as possible.</p></div></section>
    <main class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 grid lg:grid-cols-3 gap-10"><aside class="lg:col-span-1"><h2 class="text-2xl font-display font-bold text-gray-900 dark:text-white">Contact details</h2><div class="mt-6 space-y-6 text-gray-600 dark:text-gray-300"><div><h3 class="font-semibold text-gray-900 dark:text-white">Customer support</h3><a class="link" href="mailto:support@finder.example">support@finder.example</a></div><div><h3 class="font-semibold text-gray-900 dark:text-white">Response time</h3><p>We aim to respond within 1–2 business days.</p></div><div><h3 class="font-semibold text-gray-900 dark:text-white">Order help</h3><p>Please include your order number so we can help faster.</p></div></div></aside><section class="lg:col-span-2 card p-6 sm:p-8">@if (sent()) { <div class="text-center py-10"><h2 class="text-2xl font-display font-bold text-gray-900 dark:text-white">Thanks for reaching out.</h2><p class="mt-3 text-gray-600 dark:text-gray-300">This form is ready to connect to your support service. Until then, please email support&#64;finder.example.</p></div> } @else { <h2 class="text-2xl font-display font-bold text-gray-900 dark:text-white mb-6">Send a message</h2><form (ngSubmit)="submit()" #contactForm="ngForm" class="space-y-5"><div class="grid sm:grid-cols-2 gap-5"><label class="block text-sm font-medium text-gray-700 dark:text-gray-200">First name<input class="input-field mt-2" name="firstName" required autocomplete="given-name" [(ngModel)]="firstName"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-200">Email address<input class="input-field mt-2" type="email" name="email" required email autocomplete="email" [(ngModel)]="email"></label></div><label class="block text-sm font-medium text-gray-700 dark:text-gray-200">Order number <span class="text-gray-400">(optional)</span><input class="input-field mt-2" name="orderNumber" [(ngModel)]="orderNumber"></label><label class="block text-sm font-medium text-gray-700 dark:text-gray-200">How can we help?<textarea class="input-field mt-2 min-h-32" name="message" required [(ngModel)]="message"></textarea></label><button type="submit" class="btn-primary" [disabled]="contactForm.invalid">Send message</button></form> }</section></main>`
})
export class ContactComponent {
  firstName = ''; email = ''; orderNumber = ''; message = ''; sent = signal(false);
  submit() { this.sent.set(true); }
}
